Got all of the verbs working for Customers. There are 3 GETs, a Post,…
chicken-sloths/bangazon-api-sprint1 pull request #101
Opened 2018-03-23 20:53 UTC by joechesney

… and a PUT

# Description
Got all of the verbs working for Customers. There are 3 GETs, a Post, and a Put.

## Number of Fixes
Fixes #1 

## Related Ticket(s)
#1 

## Problem to Solve
Gives users access to the Customers Table

## Expected Behavior
Should correctly Get all customers, or Get a single customer, or Get all customers that have not placed an order, or Post a new customer to the Customers table, or Put new property values onto an existing customer.

## Steps to Test Solution

1. To test the GET allCustomers function, go to `http://127.0.0.1:8080/api/v1/customers` and there should be all of the customers listed, which I believe is 25 total customers. 
2. To test the GET oneCustomer function, go to `http://127.0.0.1:8080/api/v1/customers/15` (or replace the number 15 in the url with any number between 0 and 24, and there should be one customer listed, and their customer_id should match the number you typed into the url.

## Testing

[ ] There are new unit tests in this PR, and I verify that there is full coverage of all new code.
[ ] I certify that all existing tests pass

## Documentation
[x] There is new documentation in this pull request that must be reviewed..
[ ] I added documentation for any new classes/methods

2018-03-24 11:14 UTC, jordan-castelloe commented on routes/products/customers.js
> +customersRouter.get('/:id', getOneCustomer);
This didn't work for me, but I changed it to ``/customers/:id`` and that made everything work!

2018-03-24 11:19 UTC, jordan-castelloe requested changes
Add ``/customers`` to your routes in ``routes/products/customers.js`` or ``routes/products/index.js``! I added that on my local version of your branch and tested again and everything else worked like a charm.

2018-03-24 11:22 UTC, jordan-castelloe commented
Also, for the next person who tests this branch, here's the JSON I used for POST and PUT so you don't have to write it again.
`` {
"first_name": "Nicolas",
"last_name": "Cage",
"account_creation_date": "2018-03-22T15:52:23.254Z",
"street_address": "123 Awesome Street",
"city": "Crab Apple",
"state": "North Carolina",
"postal_code": "100000",
"phone_number": "(042) 494-3771 x385"
} ``

2018-03-24 11:24 UTC, jordan-castelloe commented
Also, @joechesney: it looks like you checked a box that there's new documentation in this pr that I should review, but I wasn't sure where to look. Happy to look at it, just point me in the right direction!

2018-03-24 11:45 UTC, jordan-castelloe commented on routes/products/customers.js
> +customersRouter.get('/:id', getOneCustomer);
OH okay wait I just looked at David's PR and he added it in the index file for his sub-folder! I didn't even think of that, but that works too! That might have been what you were doing and just forgot to commit the index file with the ``/customers`` route in it?

2018-03-25 19:03 UTC, DavidLarsKetch commented on routes/products/customers.js
> +customersRouter.get('/:id', getOneCustomer);
Yeah @kenziebottoms has been doing that I really liked it, so stole it from them.

2018-03-25 19:05 UTC, kenziebottoms commented on routes/products/customers.js
> +customersRouter.get('/:id', getOneCustomer);
:star2:

2018-03-25 19:09 UTC, DavidLarsKetch commented
Don't forget to test `[](http://localhost:8080/api/v1/customers?active=false)`!

2018-03-25 19:11 UTC, DavidLarsKetch commented on routes/products/customers.js
> +customersRouter.get('/:id', getOneCustomer);
Ditto what @jordan-castelloe. Everything works :100: once you throw `/customers` into `routes/products`

2018-03-25 19:12 UTC, DavidLarsKetch commented on controllers/products/customersCtrl.js
> +  console.log('req body',req.body);
Get rid of dat stank

2018-03-25 19:13 UTC, DavidLarsKetch requested changes
Same what @jordan-castelloe said and that one left in `console.log` in `customersCtrl`

2018-03-26 14:17 UTC, kenziebottoms commented
testing

2018-03-26 14:19 UTC, kenziebottoms approved these changes

2018-03-26 14:35 UTC, merged