putProduct(), postProduct(), and deleteProduct()
chicken-sloths/bangazon-api-sprint1 pull request #102
Opened 2018-03-23 21:05 UTC by TimAConner

# Description
Completed the endpoints for /products.  Added putProduct, postProduct, and deleteProduct models, controllers, and routes.

## Related Ticket(s)
Completed Issue #2  (Allow developers to access product endpoints)

## Expected Behavior
1. putProduct should insert a row if one doesn't exist at the specified id, or it should overwrite it if it does exist.  If not all data is given, it will throw an error.
1. postProduct will insert a new product to the end of the table.
1. deleteProduct will delete the id passed to it.

## Steps to Test Solution

1. Comment out employees routes and all other product routes other than product.js.
1.  In Postman, use `POST` with the URL `http://localhost:8080/api/v1/products/ `
     1. Body:
      ``` {
	"price": "199999999.99",
	"title": "The Red Jewel",
	"description": "A red jewel",
	"product_type_id": "1",
	"creator_id": "1"
     }```
     1. Should return the id of the product if successful.
1.  In Postman, use `PUT` with the URL `http://localhost:8080/api/v1/products/50 `
     1. Body:
      ``` {
	"price": "199999999.99",
	"title": "The Red Jewel",
	"description": "A red jewel",
	"product_type_id": "1",
	"creator_id": "1"
     }```
     1. Should return the id of the product if successful.
1.  In Postman, use `DELETE` with the URL `http://localhost:8080/api/v1/products/50 `
     1. Should return the id of the delete value if successful.

2018-03-23 22:45 UTC, DavidLarsKetch commented on routes/products/products.js
> +productsRouter.post('/products/', postProduct);
Just curious, not saying anything needs to change. If someone were to write another router that extended this `URL` and began that route with `/new-thing` would this break since it's expecting `api/v1/products//new-thing`?

2018-03-23 22:55 UTC, DavidLarsKetch requested changes
Everything works :100:, but check real quick on those `this` & `() =>` crap.

2018-03-23 22:55 UTC, DavidLarsKetch commented on models/products/ProductsModel.js
> +    )`, err => err ? reject(err) : resolve(this.lastID));
Same as above, `this` and `() =>` bullshit.

2018-03-23 22:55 UTC, DavidLarsKetch commented on models/products/ProductsModel.js
> +      err => err ? reject(err) : resolve(id));
As much as I love arrow functions, this has to be a regular `function(err)` for `this` to work.

2018-03-23 22:55 UTC, DavidLarsKetch commented on models/products/ProductsModel.js
> +      err => err ? reject(err) : resolve(id));
See below, however, here `this.changes` would be more informative of a 'success' message than simply returning the ID that is passed into the function.

2018-03-23 23:03 UTC, TimAConner commented on routes/products/products.js
> +productsRouter.post('/products/', postProduct);
I'm unsure!  I'll remove the extra forward slashes.  I wonder if it will work if after I remove the '/' I then add a '/' to the URL.  For example: "localhost:8080/api/v1/products/".

2018-03-24 11:37 UTC, jordan-castelloe approved these changes
Looks good! Everything worked for me!

2018-03-25 18:04 UTC, DavidLarsKetch approved these changes
:+1: Beautiful PR @TimAConner!

2018-03-26 14:08 UTC, merged