Fixes #5: GET, POST, PUT, & DELETE for Product_Types
chicken-sloths/bangazon-api-sprint1 pull request #104
Opened 2018-03-23 22:38 UTC by DavidLarsKetch

# Description
Users can make requests to `GET`, `POST`, `PUT`, & `DELETE` data for `Product_Types`

## Number of Fixes
1

## Related Ticket(s)
Fixes #5, follows reqs in #103 

## Problem to Solve
Users were not able to interact with the data stored `Product_Types`

## Proposed Changes
Using `ProductTypesModel`, `productTypesCtrl`, and `routes/products/product-types`, requests to `GET`, `POST`, `PUT`, & `DELETE` are correctly handled, returning appropriate data to the user in `JSON` format

## Expected Behavior
`GET` `product-type` returns all product-types

`GET` `product-type/:id` returns the product-type matching requested ID

`POST` `product-type` `{ "title": [new-product-type] }` adds that product type to the database

`PUT` `product-type/:id` `{ "title": [new-title] }` edits the title for the product type matching requested ID

`DELETE` `product-type/:id` deletes the product type matching that ID

## Steps to Test Solution
1. (optional) Reset DB: `npm run db:generate`

1. `npm start`

1. `GET` `localhost:8080/api/v1/product-type` should return all data in `Product_Types`, confirm by searching DB in db browser with `SELECT * FROM Product_Types`

1. `GET` `localhost:8080/api/v1/product-type/4` should return `{ "product_type_id": 4, "title": "Health" }

1. `POST` `localhost:8080/api/v1/product-type` with this payload:
```
{
  "title": "Furniture"
}
```
Should return: `10` (new ID)

6. `PUT` `localhost:8080/api/v1/product-type/7` with this payload:
```
{
  "title": "The Good Stuff"
}
```
Should return: `7`
Run: `localhost:8080/api/v1/product-type/7` to confirm `title` changed to `The Good Stuff`

7. `DELETE` `localhost:8080/api/v1/product-type/3` should return: `1`
Run: `localhost:8080/api/v1/product-type/3` to confirm nothing is returned

## Testing

[x] There are new unit tests in this PR, and I verify that there is full coverage of all new code.
[x] I certify that all existing tests pass

2018-03-24 11:47 UTC, jordan-castelloe approved these changes
Everything works, awesome testing instructions, 100% groovy

2018-03-24 17:20 UTC, kenziebottoms requested changes
This works great, but doesn't follow the naming conventions of the endpoints. Should be `/product-types`

2018-03-25 18:14 UTC, DavidLarsKetch commented
Alright should be fixed up! Thanks for catching that @kenziebottoms

2018-03-25 18:47 UTC, kenziebottoms approved these changes

2018-03-25 19:16 UTC, merged