`/training-programs` endpoints
chicken-sloths/bangazon-api-sprint1 pull request #105
Opened 2018-03-24 17:33 UTC by kenziebottoms

# Description
Adds the following endpoints:
- `GET /training-programs`: gets all training programs
- `GET /training-programs/:id`: gets one training program by id
- `POST /training-programs`: posts new training program
- `PUT /training-programs/:id`: replaces/updates one training program by id
- `DELETE /training-programs/:id`: removes one training program by id

## Related Ticket(s)
fixes #59, fixes #9 

## Steps to Test Solution
1. `npm run db:generate`
1. comment out non-training program routes
1. http://localhost:8080/api/v1/training-programs should give you training programs with ids 0-9
1. http://localhost:8080/api/v1/training-programs/3 should give you a training program called `Brand 101`
1. `POST http://localhost:8080/api/v1/training-programs`:
  ```json
  {"max_capacity":17,"start_date":"2017-11-23T21:57:41.704Z","end_date":"2018-02-20T02:15:39.657Z","name":"Star Wars 101"}
  ```
  should return `10`
1. http://localhost:8080/api/v1/training-programs/10 should now give you the Star Wars training program
1. `PUT http://localhost:8080/api/v1/training-programs/3`:
  ```json
  {"max_capacity":17,"start_date":"2017-11-23T21:57:41.704Z","end_date":"2018-02-20T02:15:39.657Z","name":"Star Wars 101"}
  ```
  should return `3` and http://localhost:8080/api/v1/training-programs/3 should now give you the Star Wars training program
1. `PUT http://localhost:8080/api/v1/training-programs/31`:
  ```json
  {"max_capacity":17,"start_date":"2017-11-23T21:57:41.704Z","end_date":"2018-02-20T02:15:39.657Z","name":"Star Wars 101"}
  ```
  should return `31` and http://localhost:8080/api/v1/training-programs/31 should now give you the Star Wars training program
1. `DELETE http://localhost:8080/api/v1/training-programs/31` should return `31` and http://localhost:8080/api/v1/training-programs/31 should now give you a "Training program not found" error

2018-03-25 18:14 UTC, DavidLarsKetch commented
testing!

2018-03-25 18:33 UTC, DavidLarsKetch commented on models/employees/TrainingProgramsModel.js
> +      resolve(id);
I'll say the same thing about @TimAConner 's PR #102, and I'm curious about what you think @kenziebottoms.

With `DELETE`, if there isn't anything at `id`, it doesn't throw an error, and here would `resolve(id)`. The `id` being sent back is the same `id` being passed into `deleteTrainingProgram`. So, it could make a user think that they did actually delete something when there wasn't anything at that `id` in the db. What do you think about using `this.changes` instead (meaning, making it not `() =>` function)?

2018-03-25 18:35 UTC, DavidLarsKetch requested changes
It all works :100: . See my one comment. If you think it's unimportant, then you have my :+1: . I'm mostly curious what you think.

2018-03-25 18:48 UTC, kenziebottoms commented on models/employees/TrainingProgramsModel.js
> +      resolve(id);
Hmmmm yeah this is a good point and probably something we need to go back and double-check with all of them. I agree there should be some noise if you try to delete something that doesn't exist.

2018-03-25 18:59 UTC, kenziebottoms commented on models/employees/TrainingProgramsModel.js
> +      resolve(id);
@DavidLarsKetch It now throws an error if you try to delete an ID that doesn't exist.

2018-03-25 19:15 UTC, DavidLarsKetch commented on models/employees/TrainingProgramsModel.js
> +      resolve(id);
Awesome!

2018-03-25 19:16 UTC, DavidLarsKetch approved these changes
:+1:

2018-03-26 14:06 UTC, jordan-castelloe commented
testing!

2018-03-26 14:20 UTC, jordan-castelloe approved these changes
woohoo! it all works!

2018-03-26 14:22 UTC, merged