Orders Endpoints
chicken-sloths/bangazon-api-sprint1 pull request #106
Opened 2018-03-24 20:52 UTC by jordan-castelloe

# Description
Adds the following endpoints:
- `GET /orders`: gets all orders
- `GET /orders/:id`: gets one order by id
- `POST /order`: posts new order
- `PUT /orders/:id`: updates one order by id
- `DELETE /orders/:id`: removes one order by id

## Related Ticket(s)
fixes #4 (still need to deal with issue #10) 

## Steps to Test Solution
1. `npm run db:generate`

1. Comment out non-orders routes

1. `` npm start`` to start your server.

1. ``http://localhost:8080/api/v1/orders`` should give you all the orders with a stringified list of the products on that order

1. ``http://localhost:8080/api/v1/orders/10`` should give you all the products on that order, plus order information for each product. (I realize this is glitchy! Eventually, it'll go into an array format, but this will tide us over until then.)

1. POST the following JSON to `http://localhost:8080/api/v1/orders`:
`` {
        "customer_id": 0,
        "payment_option_id": 100
    }``
**Should return**:`35` 

1. PUT the following JSON to ``http://localhost:8080/api/v1/orders/1`` 
`` {
        "customer_id": 0,
        "payment_option_id": 100
    }``
**Run a`GET` for `http://localhost:8080/api/v1/orders/1`.** You should see that the customer_ids and payment_option_ids on each product object have changed to 0 and 100, respectively.

1. Run a DELETE  on `http://localhost:8080/api/v1/orders/35` and it should return `35`

## A couple other notes
I didn't do error handling on the orders route because I figure when orders are created they won't have a payment_type_id? And then that'll get added later? I honestly can't remember if we decided on a way to handle that or not. If anyone remembers or has a concrete idea, I'd be glad to include it on this PR. Otherwise, we can go ahead and merge this in for basic MVP functionality and work out the details post-MVP.

2018-03-25 18:36 UTC, DavidLarsKetch commented
testing!

2018-03-25 19:02 UTC, DavidLarsKetch requested changes
Check my one comment. Otherwise, you have my :+1:

2018-03-25 19:02 UTC, DavidLarsKetch commented on models/products/OrdersModel.js
> +            order.Products = productData
So I'm getting a `TypeError` with this line when I `DELETE` and then `GET` a single order. The reason, _I think_, is because if there is an `err`, line `40` would still run. However, `productData` would be `undefined` because there is an `err`, thus throwing a `TypeError`. I'm not sure how to refactor this, but something like `order.products = err ? [] : productData` might be a better choice.

2018-03-25 21:44 UTC, jordan-castelloe commented on models/products/OrdersModel.js
> +            order.Products = productData
Oh yep good catch. That makes total sense. I'll switch that and push it back up!

2018-03-26 12:09 UTC, jordan-castelloe commented
Fixed the bug with deleting and getting orders (thanks @DavidLarsKetch)! Now you should be able to delete an order, try to get the same order, and get a friendly 404 error back. I just realized we should probably delete all associated products and product_orders when we delete an order, but I think that might be a new PR/ new issue for the sake of expediency

2018-03-26 14:16 UTC, DavidLarsKetch approved these changes
:+1: Super cool!

2018-03-26 14:20 UTC, kenziebottoms commented
testing

2018-03-26 14:25 UTC, TimAConner approved these changes
Fine and Dandy!

2018-03-26 14:28 UTC, merged